#!/bin/bash

#echo; date; echo $0

gnome-terminal --geometry=80x29-0+0 -- ./bin/env 0
#gnome-terminal --geometry=80x29+0+0 -x gdb -q -x scripts/gdb-run --args ./bin/env 0

sleep 0.5
gnome-terminal --geometry=80x29-0-0 -- ./bin/base

sleep 0.5
gnome-terminal --geometry=80x29+0+0 -- ./bin/float 1004
gnome-terminal --geometry=80x29+0-0 -- ./bin/float 1005
gnome-terminal --geometry=80x29+600+0 -- ./bin/float 1006
gnome-terminal --geometry=80x29+600-0 -- ./bin/float 1007
gnome-terminal --geometry=80x29+1250+0 -- ./bin/float 1008
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1009
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1010
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1011
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1012
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1013
sleep 0.5
gnome-terminal --geometry=80x29+0+0 -- ./bin/float 1014
gnome-terminal --geometry=80x29+0-0 -- ./bin/float 1015
gnome-terminal --geometry=80x29+600+0 -- ./bin/float 1016
gnome-terminal --geometry=80x29+600-0 -- ./bin/float 1017
gnome-terminal --geometry=80x29+1250+0 -- ./bin/float 1018
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1019
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1020
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1021
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1022
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1023

sleep 0.5
gnome-terminal --geometry=80x29+0+0 -- ./bin/float 1024
gnome-terminal --geometry=80x29+0-0 -- ./bin/float 1025
gnome-terminal --geometry=80x29+600+0 -- ./bin/float 1026
gnome-terminal --geometry=80x29+600-0 -- ./bin/float 1027
gnome-terminal --geometry=80x29+1250+0 -- ./bin/float 1028
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1029
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1030
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1031
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1032
gnome-terminal --geometry=80x29+1250-0 -- ./bin/float 1033

sleep 0.5
#./bin/cli start
#gnome-terminal --geometry=20x6-0+0 -x ./scripts/gtk-ctrl.sh &
nice -n1 ./bin/gui -geometry 600x470-0+0 &
